'use client'

import { type FC, useState, useEffect, useCallback } from 'react'
import {
  Activity, Shield, FileText, Users, Target,
  AlertTriangle, Zap, Handshake, Copy, Mail,
  Printer, Check, BarChart3, BookOpen, Inbox,
} from 'lucide-react'
import { Card } from '@/components/ui/Card'
import { Badge } from '@/components/ui/Badge'
import { BriefSection } from '@/components/brief/BriefSection'
import { KeyMetricHighlight } from '@/components/brief/KeyMetricHighlight'
import { formatCurrency, formatDate } from '@/lib/exports'
import type { EnrichedWeeklyBrief } from '@/lib/weekly-brief'
import type { Signal } from '@/types'

// ─── Props ──────────────────────────────────────────────────────────

interface WeeklyBriefProps {
  weekStart?: string
  weekEnd?: string
}

// ─── Signal Type Badge Mapping ──────────────────────────────────────

const SIGNAL_BADGE_VARIANT: Record<string, 'amber' | 'blue' | 'green' | 'red' | 'purple' | 'gray'> = {
  regulatory: 'red',
  competitor: 'purple',
  prospect: 'blue',
  conference: 'green',
  research: 'amber',
  incident: 'red',
}

// ─── Markdown Generator ─────────────────────────────────────────────

function briefToMarkdown(brief: EnrichedWeeklyBrief): string {
  const lines: string[] = [
    '# Weekly GTM Brief',
    `**${brief.weekStart} — ${brief.weekEnd}**`,
    '',
    '## Key Metric',
    `**${brief.keyMetric.name}:** ${brief.keyMetric.value}`,
    brief.keyMetricContext,
    '',
    '## Executive Summary',
    `- ${brief.newSignals.length} new signals detected`,
    `- Pipeline: ${brief.pipelineMovement.advanced} advanced, ${brief.pipelineMovement.stalled} stalled, ${brief.pipelineMovement.lost} lost. Total value: ${brief.pipelineValueChange}`,
    `- Engagements: ${brief.engagementHealth.healthy} healthy, ${brief.engagementHealth.atRisk} at risk, ${brief.engagementHealth.critical} critical`,
    `- Predictions: ${brief.predictionSummary.confirmed} confirmed. Accuracy: ${brief.predictionSummary.accuracy}%`,
    `- EU AI Act: ${brief.euAiActDays} days remaining`,
    '',
    '## Signals This Week',
    ...brief.newSignals.map((s) => `- **[${s.type.toUpperCase()}]** ${s.title} (actionability: ${s.actionability_score})`),
    '',
    '## Pipeline Movement',
    `- Advanced: ${brief.pipelineMovement.advanced}`,
    `- Stalled: ${brief.pipelineMovement.stalled}`,
    `- Lost: ${brief.pipelineMovement.lost}`,
    `- New entries: ${brief.pipelineNewEntries}`,
    '',
    '## Engagement Health',
    `- Healthy: ${brief.engagementHealth.healthy}`,
    `- At Risk: ${brief.engagementHealth.atRisk}`,
    `- Critical: ${brief.engagementHealth.critical}`,
    '',
    '## Priority Targets',
    ...brief.priorityTargets.map((p) => `- **${p.name}** (${p.industry}) — ${p.pipeline_stage} — ${formatCurrency(p.pipeline_value)}`),
    '',
    '## EU AI Act Countdown',
    `${brief.euAiActDays} days remaining. ${brief.euAiActMessage}`,
    '',
    '---',
    '*Generated by Forge*',
  ]
  return lines.join('\n')
}

// ─── Signal Row Component ───────────────────────────────────────────

const SignalRow: FC<{ signal: Signal }> = ({ signal }) => (
  <div className="flex items-start gap-3 py-3 border-b border-border-subtle last:border-b-0">
    <Badge variant={SIGNAL_BADGE_VARIANT[signal.type] ?? 'gray'} size="sm">
      {signal.type}
    </Badge>
    <div className="flex-1 min-w-0">
      <div className="text-sm text-text-primary font-medium truncate">{signal.title}</div>
      <div className="text-xs text-text-secondary mt-0.5 line-clamp-2">{signal.description}</div>
      {signal.suggested_action && (
        <div className="text-xs text-text-tertiary mt-1 italic">→ {signal.suggested_action}</div>
      )}
    </div>
    <div className="text-xs font-mono text-text-tertiary whitespace-nowrap">
      {signal.actionability_score}
    </div>
  </div>
)

// ─── Empty State ────────────────────────────────────────────────────

const EmptyState: FC<{ message: string; icon: React.ReactNode }> = ({ message, icon }) => (
  <div className="flex flex-col items-center justify-center py-8 text-text-tertiary">
    {icon}
    <span className="text-sm mt-2">{message}</span>
  </div>
)

// ─── Main Component ─────────────────────────────────────────────────

export const WeeklyBrief: FC<WeeklyBriefProps> = ({ weekStart, weekEnd }) => {
  const [brief, setBrief] = useState<EnrichedWeeklyBrief | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  const fetchBrief = useCallback(async (): Promise<void> => {
    setLoading(true)
    setError(null)
    try {
      const params = new URLSearchParams()
      if (weekStart) params.set('weekStart', weekStart)
      if (weekEnd) params.set('weekEnd', weekEnd)
      const qs = params.toString()
      const res = await fetch(`/api/brief${qs ? `?${qs}` : ''}`)
      if (!res.ok) {
        const body = await res.json() as { error?: string }
        throw new Error(body.error ?? 'Failed to load brief')
      }
      const body = await res.json() as { data: EnrichedWeeklyBrief }
      setBrief(body.data)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to load brief')
    } finally {
      setLoading(false)
    }
  }, [weekStart, weekEnd])

  useEffect(() => {
    void fetchBrief()
  }, [fetchBrief])

  const handleCopy = useCallback((): void => {
    if (!brief) return
    const md = briefToMarkdown(brief)
    navigator.clipboard.writeText(md).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }).catch(() => {
      // Clipboard API unavailable
    })
  }, [brief])

  const handleEmail = useCallback((): void => {
    if (!brief) return
    const subject = encodeURIComponent(`Weekly GTM Brief: ${brief.weekStart} — ${brief.weekEnd}`)
    const body = encodeURIComponent([
      `Weekly GTM Brief: ${brief.weekStart} — ${brief.weekEnd}`,
      '',
      `Key Metric: ${brief.keyMetric.name} — ${brief.keyMetric.value}`,
      '',
      `Signals: ${brief.newSignals.length} new`,
      `Pipeline: ${brief.pipelineMovement.advanced} advanced, ${brief.pipelineMovement.stalled} stalled, ${brief.pipelineMovement.lost} lost`,
      `Engagements: ${brief.engagementHealth.healthy} healthy, ${brief.engagementHealth.atRisk} at risk, ${brief.engagementHealth.critical} critical`,
      `EU AI Act: ${brief.euAiActDays} days remaining`,
      '',
      'Full brief available in Forge.',
    ].join('\n'))
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self')
  }, [brief])

  const handlePrint = useCallback((): void => {
    window.print()
  }, [])

  // ─── Loading State ──────────────────────────────────────────────

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="h-8 w-64 bg-elevated rounded animate-pulse" />
        <div className="h-4 w-48 bg-elevated rounded animate-pulse" />
        <div className="h-40 bg-elevated rounded-md animate-pulse" />
        <div className="grid grid-cols-3 gap-4">
          {[1, 2, 3].map((i) => (
            <div key={i} className="h-24 bg-elevated rounded-md animate-pulse" />
          ))}
        </div>
        <div className="space-y-3">
          {[1, 2, 3, 4].map((i) => (
            <div key={i} className="h-16 bg-elevated rounded-md animate-pulse" />
          ))}
        </div>
      </div>
    )
  }

  // ─── Error State ────────────────────────────────────────────────

  if (error || !brief) {
    return (
      <Card className="text-center py-12">
        <AlertTriangle size={24} className="mx-auto text-[#8A2020] mb-3" />
        <div className="text-sm text-text-primary font-medium mb-1">Failed to generate brief</div>
        <div className="text-xs text-text-secondary mb-4">{error ?? 'Unknown error'}</div>
        <button
          type="button"
          onClick={() => void fetchBrief()}
          className="h-9 px-4 text-sm font-medium rounded-md border border-border-default text-text-primary hover:bg-elevated transition-colors duration-150"
        >
          Retry
        </button>
      </Card>
    )
  }

  // ─── Executive Summary Bullets ──────────────────────────────────

  const summaryBullets = [
    `${brief.newSignals.length} new signal${brief.newSignals.length !== 1 ? 's' : ''} detected${brief.competitorActivity.length > 0 ? `, ${brief.competitorActivity.length} competitive` : ''}`,
    `Pipeline: ${brief.pipelineMovement.advanced} advanced, ${brief.pipelineMovement.stalled} stalled, ${brief.pipelineMovement.lost} lost. Total value: ${brief.pipelineValueChange}`,
    `Engagements: ${brief.engagementHealth.healthy} healthy, ${brief.engagementHealth.atRisk} at risk, ${brief.engagementHealth.critical} critical`,
    `Predictions: ${brief.predictionSummary.confirmed} confirmed this week. Overall accuracy: ${brief.predictionSummary.accuracy}%`,
    `EU AI Act: ${brief.euAiActDays} days remaining`,
  ]

  // ─── Render ─────────────────────────────────────────────────────

  return (
    <>
      {/* Print-only styles */}
      <style>{`
        @media print {
          nav, header, [data-actions-bar], .no-print { display: none !important; }
          body { background: white !important; color: black !important; }
          * { border-color: #ddd !important; }
          section { break-inside: avoid; }
        }
      `}</style>

      <div className="space-y-8">
        {/* Header */}
        <div className="flex items-start justify-between">
          <div>
            <h1 className="font-display text-2xl font-semibold text-text-primary tracking-tight">
              Weekly GTM Brief
            </h1>
            <p className="text-sm text-text-secondary mt-1">
              {formatDate(brief.weekStart, 'long')} — {formatDate(brief.weekEnd, 'long')}
            </p>
            <p className="text-xs text-text-tertiary mt-0.5">
              Generated by Forge · {formatDate(new Date().toISOString().slice(0, 10), 'long')}
            </p>
          </div>
          <Badge variant="red" size="md">
            <Shield size={12} className="mr-1 inline" />
            EU AI Act: {brief.euAiActDays}d
          </Badge>
        </div>

        {/* Key Metric Hero */}
        <KeyMetricHighlight
          name={brief.keyMetric.name}
          value={brief.keyMetric.value}
          trend={brief.keyMetric.trend}
          context={brief.keyMetricContext}
        />

        {/* Executive Summary */}
        <Card>
          <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mb-3">
            Executive Summary
          </div>
          <ul className="space-y-2">
            {summaryBullets.map((bullet, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-text-primary">
                <span className="text-text-tertiary mt-0.5">•</span>
                <span>{bullet}</span>
              </li>
            ))}
          </ul>
        </Card>

        {/* Signals This Week */}
        <BriefSection title="Signals This Week" icon={<Zap size={14} />} priority={brief.newSignals.length > 3 ? 'high' : 'normal'}>
          {brief.newSignals.length > 0 ? (
            <div>
              {brief.newSignals.map((signal) => (
                <SignalRow key={signal.id} signal={signal} />
              ))}
            </div>
          ) : (
            <EmptyState message="No new signals detected this week" icon={<Inbox size={20} />} />
          )}
        </BriefSection>

        {/* Pipeline Movement */}
        <BriefSection title="Pipeline Movement" icon={<BarChart3 size={14} />} priority={brief.pipelineMovement.lost > 0 ? 'high' : 'normal'}>
          <div className="grid grid-cols-4 gap-4">
            <Card>
              <div className="text-2xl font-mono font-semibold text-[#3D6B35]">
                {brief.pipelineMovement.advanced}
              </div>
              <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mt-1">
                Advanced
              </div>
            </Card>
            <Card>
              <div className="text-2xl font-mono font-semibold text-[#8A6B20]">
                {brief.pipelineMovement.stalled}
              </div>
              <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mt-1">
                Stalled
              </div>
            </Card>
            <Card>
              <div className="text-2xl font-mono font-semibold text-[#8A2020]">
                {brief.pipelineMovement.lost}
              </div>
              <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mt-1">
                Lost
              </div>
            </Card>
            <Card>
              <div className="text-2xl font-mono font-semibold text-text-primary">
                {brief.pipelineNewEntries}
              </div>
              <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mt-1">
                New Entries
              </div>
            </Card>
          </div>
          <div className="text-sm text-text-secondary mt-3">
            Total pipeline value: <span className="font-mono font-medium text-text-primary">{brief.pipelineValueChange}</span>
          </div>
        </BriefSection>

        {/* Engagement Health */}
        <BriefSection title="Engagement Health" icon={<Activity size={14} />} priority={brief.engagementHealth.critical > 0 ? 'high' : 'normal'}>
          <div className="grid grid-cols-3 gap-4">
            <Card>
              <div className="text-2xl font-mono font-semibold text-[#3D6B35]">
                {brief.engagementHealth.healthy}
              </div>
              <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mt-1">
                Healthy
              </div>
              <div className="mt-2 h-1.5 rounded-full bg-[#D4E7D0]">
                <div className="h-full rounded-full bg-[#3D6B35]" style={{ width: '100%' }} />
              </div>
            </Card>
            <Card>
              <div className="text-2xl font-mono font-semibold text-[#8A6B20]">
                {brief.engagementHealth.atRisk}
              </div>
              <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mt-1">
                At Risk
              </div>
              <div className="mt-2 h-1.5 rounded-full bg-[#EDE0C8]">
                <div className="h-full rounded-full bg-[#8A6B20]" style={{ width: '100%' }} />
              </div>
            </Card>
            <Card>
              <div className="text-2xl font-mono font-semibold text-[#8A2020]">
                {brief.engagementHealth.critical}
              </div>
              <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mt-1">
                Critical
              </div>
              <div className="mt-2 h-1.5 rounded-full bg-[#EDCFCF]">
                <div className="h-full rounded-full bg-[#8A2020]" style={{ width: '100%' }} />
              </div>
            </Card>
          </div>
        </BriefSection>

        {/* Prediction Track Record */}
        <BriefSection title="Prediction Track Record" icon={<Target size={14} />}>
          <div className="grid grid-cols-4 gap-4">
            <Card>
              <div className="text-2xl font-mono font-semibold text-text-primary">
                {brief.predictionSummary.total}
              </div>
              <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mt-1">
                Total
              </div>
            </Card>
            <Card>
              <div className="text-2xl font-mono font-semibold text-[#3D6B35]">
                {brief.predictionSummary.confirmed}
              </div>
              <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mt-1">
                Confirmed
              </div>
            </Card>
            <Card>
              <div className="text-2xl font-mono font-semibold text-[#8A2020]">
                {brief.predictionSummary.refuted}
              </div>
              <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mt-1">
                Refuted
              </div>
            </Card>
            <Card>
              <div className="text-2xl font-mono font-semibold text-text-primary">
                {brief.predictionSummary.accuracy}<span className="text-lg">%</span>
              </div>
              <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium mt-1">
                Accuracy
              </div>
            </Card>
          </div>
        </BriefSection>

        {/* Content Published */}
        <BriefSection title="Content Published" icon={<BookOpen size={14} />} defaultOpen={brief.contentPublished.length > 0}>
          {brief.contentPublished.length > 0 ? (
            <div className="space-y-2">
              {brief.contentPublished.map((item) => (
                <div key={item.id} className="flex items-center gap-3 py-2 border-b border-border-subtle last:border-b-0">
                  <Badge variant={item.type === 'research' ? 'amber' : item.type === 'regulatory' ? 'red' : item.type === 'competitive' ? 'purple' : 'blue'} size="sm">
                    {item.type}
                  </Badge>
                  <div className="flex-1 min-w-0">
                    <div className="text-sm text-text-primary font-medium truncate">{item.title}</div>
                    <div className="text-xs text-text-tertiary">{formatDate(item.date, 'short')}</div>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <EmptyState message="No content published this week" icon={<FileText size={20} />} />
          )}
        </BriefSection>

        {/* Channel Partnerships */}
        <BriefSection title="Channel Partnerships" icon={<Handshake size={14} />} defaultOpen={brief.channelHighlights.statusChanges.length > 0}>
          <div className="flex items-center gap-6 mb-4">
            <div className="text-sm text-text-secondary">
              Active: <span className="font-mono font-medium text-text-primary">{brief.channelHighlights.activePartners}</span>
              <span className="text-text-tertiary"> / {brief.channelHighlights.totalPartners} total</span>
            </div>
          </div>
          {brief.channelHighlights.statusChanges.length > 0 ? (
            <div className="space-y-2">
              {brief.channelHighlights.statusChanges.map((evt) => (
                <div key={evt.id} className="flex items-center gap-2 text-sm py-1.5 border-b border-border-subtle last:border-b-0">
                  <Badge variant="blue" size="sm">status change</Badge>
                  <span className="text-text-primary">
                    {(evt.payload['partnerName'] as string) ?? evt.entity_id}
                  </span>
                  {typeof evt.payload['from'] === 'string' && typeof evt.payload['to'] === 'string' && (
                    <span className="text-text-tertiary text-xs">
                      {evt.payload['from']} → {evt.payload['to']}
                    </span>
                  )}
                </div>
              ))}
            </div>
          ) : (
            <EmptyState message="No partnership status changes this week" icon={<Handshake size={20} />} />
          )}
        </BriefSection>

        {/* Competitive Intelligence */}
        <BriefSection title="Competitive Intelligence" icon={<AlertTriangle size={14} />} priority={brief.competitorActivity.length > 0 ? 'high' : 'normal'} defaultOpen={brief.competitorActivity.length > 0}>
          {brief.competitorActivity.length > 0 ? (
            <div>
              {brief.competitorActivity.map((signal) => (
                <SignalRow key={signal.id} signal={signal} />
              ))}
            </div>
          ) : (
            <EmptyState message="No competitive signals detected this week" icon={<AlertTriangle size={20} />} />
          )}
        </BriefSection>

        {/* Priority Targets */}
        <BriefSection title="Priority Targets Next Week" icon={<Users size={14} />} priority="high">
          {brief.priorityTargets.length > 0 ? (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead>
                  <tr className="border-b border-border-subtle">
                    <th className="text-left text-xs uppercase tracking-wider text-text-tertiary font-medium px-4 py-2">Prospect</th>
                    <th className="text-left text-xs uppercase tracking-wider text-text-tertiary font-medium px-4 py-2">Industry</th>
                    <th className="text-right text-xs uppercase tracking-wider text-text-tertiary font-medium px-4 py-2">Priority</th>
                    <th className="text-left text-xs uppercase tracking-wider text-text-tertiary font-medium px-4 py-2">Stage</th>
                    <th className="text-right text-xs uppercase tracking-wider text-text-tertiary font-medium px-4 py-2">Value</th>
                  </tr>
                </thead>
                <tbody>
                  {brief.priorityTargets.map((prospect) => (
                    <tr key={prospect.id} className="border-b border-border-subtle last:border-b-0">
                      <td className="px-4 py-3 text-sm text-text-primary font-medium">{prospect.name}</td>
                      <td className="px-4 py-3 text-sm text-text-secondary">{prospect.industry}</td>
                      <td className="px-4 py-3 text-sm text-text-primary font-mono text-right">{prospect.priority_score}</td>
                      <td className="px-4 py-3">
                        <Badge variant="gray" size="sm">
                          {prospect.pipeline_stage.replace(/_/g, ' ')}
                        </Badge>
                      </td>
                      <td className="px-4 py-3 text-sm text-text-primary font-mono text-right">{formatCurrency(prospect.pipeline_value)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <EmptyState message="No priority targets identified" icon={<Target size={20} />} />
          )}
        </BriefSection>

        {/* EU AI Act Countdown */}
        <BriefSection title="EU AI Act Countdown" icon={<Shield size={14} />} priority={brief.euAiActDays <= 60 ? 'high' : 'normal'}>
          <div className="flex items-center gap-4 mb-3">
            <div className="text-3xl font-mono font-semibold text-text-primary">
              {brief.euAiActDays}
            </div>
            <div className="text-xs uppercase tracking-wider text-text-tertiary font-medium">
              Days Remaining
            </div>
          </div>
          <div className={`text-sm ${brief.euAiActDays <= 30 ? 'text-[#8A2020] font-medium' : brief.euAiActDays <= 60 ? 'text-[#8A6B20]' : 'text-text-secondary'}`}>
            {brief.euAiActMessage}
          </div>
        </BriefSection>

        {/* Footer */}
        <div className="text-center text-xs text-text-tertiary py-6 border-t border-border-subtle">
          This brief was generated automatically by Forge. All metrics trace to the underlying data.
        </div>

        {/* Actions Bar */}
        <div data-actions-bar className="no-print sticky bottom-0 bg-base border-t border-border-subtle py-3 -mx-8 px-8 flex items-center gap-3">
          <button
            type="button"
            onClick={handleCopy}
            className="h-9 px-4 text-sm font-medium rounded-md border border-border-default text-text-primary hover:bg-elevated transition-colors duration-150 inline-flex items-center gap-2"
          >
            {copied ? <Check size={14} /> : <Copy size={14} />}
            {copied ? 'Copied' : 'Copy as Markdown'}
          </button>
          <button
            type="button"
            onClick={handleEmail}
            className="h-9 px-4 text-sm font-medium rounded-md border border-border-default text-text-primary hover:bg-elevated transition-colors duration-150 inline-flex items-center gap-2"
          >
            <Mail size={14} />
            Share via Email
          </button>
          <button
            type="button"
            onClick={handlePrint}
            className="h-9 px-4 text-sm font-medium rounded-md border border-border-default text-text-primary hover:bg-elevated transition-colors duration-150 inline-flex items-center gap-2"
          >
            <Printer size={14} />
            Print
          </button>
          <button
            type="button"
            disabled
            className="h-9 px-4 text-sm font-medium rounded-md border border-border-default text-text-primary opacity-50 cursor-not-allowed inline-flex items-center gap-2"
            title="Coming soon"
          >
            <FileText size={14} />
            Download PDF
          </button>
        </div>
      </div>
    </>
  )
}
