'use client'

import { type FC, useState, useCallback } from 'react'
import { Copy, Mail, Calendar } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { formatDate, formatCurrency } from '@/lib/exports'
import type { Prospect } from '@/types'

interface BriefingExportProps {
  prospect: Prospect
  onCopy: () => void
  onEmail: () => void
}

function buildBriefingMarkdown(prospect: Prospect): string {
  const date = formatDate(new Date().toISOString(), 'long')
  const lines: string[] = [
    '# ASSESSMENT SCOPING BRIEFING',
    '',
    `**${prospect.name}** \u00b7 ${date}`,
    '',
    '---',
    '',
    '## Company Context',
    `- **Industry:** ${prospect.industry}`,
    `- **AI Spend:** ${formatCurrency(prospect.estimated_ai_spend)}/month`,
    `- **Pipeline Stage:** ${prospect.pipeline_stage.replace(/_/g, ' ')}`,
    `- **Pipeline Value:** ${formatCurrency(prospect.pipeline_value)}`,
    `- **Revenue Engine:** ${prospect.revenue_engine}`,
    '',
  ]

  if (prospect.model_families.length > 0) {
    lines.push(`- **Model Families:** ${prospect.model_families.join(', ')}`)
    lines.push('')
  }

  if (prospect.regulatory_exposure.length > 0) {
    lines.push(`- **Regulatory Exposure:** ${prospect.regulatory_exposure.join(', ')}`)
    lines.push('')
  }

  if (prospect.pain_points.length > 0) {
    lines.push('## Pain Points')
    for (const pain of prospect.pain_points) {
      lines.push(`- ${pain}`)
    }
    lines.push('')
  }

  if (prospect.contacts.length > 0) {
    lines.push('## Contacts')
    for (const contact of prospect.contacts) {
      lines.push(`- **${contact.name}** \u2014 ${contact.title} (${contact.persona})`)
    }
    lines.push('')
  }

  lines.push('---')
  lines.push(`*Briefing generated by Forge \u00b7 ${date} \u00b7 Confidential \u2014 GTM team only*`)

  return lines.join('\n')
}

function buildEmailBody(prospect: Prospect): string {
  const date = formatDate(new Date().toISOString(), 'short')
  return [
    `Scoping Briefing: ${prospect.name}`,
    `Date: ${date}`,
    '',
    `Industry: ${prospect.industry}`,
    `AI Spend: ${formatCurrency(prospect.estimated_ai_spend)}/month`,
    `Pipeline Value: ${formatCurrency(prospect.pipeline_value)}`,
    `Stage: ${prospect.pipeline_stage.replace(/_/g, ' ')}`,
    '',
    prospect.pain_points.length > 0 ? `Key Pain Points: ${prospect.pain_points.join(', ')}` : '',
    '',
    'Full briefing available in Forge.',
  ].filter(Boolean).join('\n')
}

function buildCalendarUrl(prospect: Prospect): string {
  const title = encodeURIComponent(`Scoping Meeting: ${prospect.name}`)
  const description = encodeURIComponent(
    `Assessment scoping conversation with ${prospect.name}.\n\nIndustry: ${prospect.industry}\nPipeline Value: ${formatCurrency(prospect.pipeline_value)}\n\nFull briefing available in Forge.`
  )
  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${description}`
}

export const BriefingExport: FC<BriefingExportProps> = ({ prospect, onCopy, onEmail }) => {
  const [copied, setCopied] = useState(false)

  const handleCopy = useCallback(async (): Promise<void> => {
    const markdown = buildBriefingMarkdown(prospect)
    await navigator.clipboard.writeText(markdown)
    setCopied(true)
    onCopy()
    setTimeout(() => setCopied(false), 2000)
  }, [prospect, onCopy])

  const handleEmail = useCallback((): void => {
    const date = formatDate(new Date().toISOString(), 'short')
    const subject = encodeURIComponent(`Scoping Briefing: ${prospect.name} \u2014 ${date}`)
    const body = encodeURIComponent(buildEmailBody(prospect))
    window.open(`mailto:?subject=${subject}&body=${body}`, '_self')
    onEmail()
  }, [prospect, onEmail])

  const handleCalendar = useCallback((): void => {
    const url = buildCalendarUrl(prospect)
    window.open(url, '_blank', 'noopener,noreferrer')
  }, [prospect])

  return (
    <div className="flex items-center gap-2">
      <Button variant="secondary" size="sm" onClick={handleCopy}>
        <Copy className="w-3.5 h-3.5 mr-1.5" />
        {copied ? 'Copied!' : 'Copy Briefing'}
      </Button>
      <Button variant="secondary" size="sm" onClick={handleEmail}>
        <Mail className="w-3.5 h-3.5 mr-1.5" />
        Email to Self
      </Button>
      <Button variant="secondary" size="sm" onClick={handleCalendar}>
        <Calendar className="w-3.5 h-3.5 mr-1.5" />
        Add to Calendar
      </Button>
    </div>
  )
}
